#!/bin/sh
#
# ~/.xinitrc
#
# # # # # # # # # # # # # #

# The source of my woes, the default being somewhat faulty, see I knew I wasn't crazy!

if [ -f "$HOME/.xprofile" ]; then
	source "$HOME/.xprofile"
fi

## Session Control
if [ $# -gt 0 ]; then
	case "$1" in
	awesome | awesomewm) exec awesome ;;
	xfce) exec xfce ;;
	i3) exec i3 ;;
	bspwm) exec bspwm ;;
	dwm) exec dwm ;;
	gnome) exec gnome-session ;;
	i3 | i3wm) exec i3 ;;
	kde) exec startplasma-x11 ;;
	lxqt) exec startlxqt ;;
	openbox) exec openbox-session ;;
	plasma) exec startplasma-wayland ;;
	xfce | xfce4) exec startxfce4 ;;
	*)
		printf %s\\n "Unknown DE/wm '$1'"
		exit 1
		;;
	esac
else
	exec xfce # this is the default choice without any arguments
fi
