#!/bin/sh
##########################################################################################################
##########################################################################################################
## Thomas Leon Highbaugh##################################################################################
## Dotfiles ##############################################################################################
## ${HOME}/.profile ######################################################################################
##########################################################################################################
##########################################################################################################
# This file setsenvironmental variables available across the shells installed on
# this system. Edit with care, breaking changes can do awesome things like break
# lightdm making logging in a challenge. Or worse....
################################################################################
## Config Directory
################################################################################
export XDG_CONFIG_HOME="$HOME/.config"


################################################################################
## Path Modification ###########################################################
################################################################################
export PATH="$XDG_CONFIG_HOME/yarn/global/node_modules/.bin:$PATH"
PATH="$HOME/bin:$PATH"
PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.yarn/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.gem/ruby/2.7.0/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"

## Editor ######################################################################
export EDITOR=/usr/bin/vim
export EDITORD=/usr/bin/vim
export GUI_EDITOR=/usr/share/applications/doom-emacs.desktop
export TERM="xterm-256color"

## QT ##########################################################################
export QT_QPA_PLATFORMTHEME="qt5ct"
export QT_AUTO_SCREEN_SCALE_FACTOR=0

## XDG #########################################################################
export XDG_CURRENT_DESKTOP=XFCE
export XDG_CONFIG_DIRS=/etc/xdg


## GOLANG ######################################################################
export GOPATH=$HOME/go
export GO15VENDOREXPERIMENT=1

## OS ##########################################################################
export TERMINFO=~/.terminfo
export tOS=`uname -s`
export ARCH=`uname -m`

## Pager #######################################################################
export PAGER="less"
export LESS="-RMin"
export RI_PAGER='less -FX'

