#!/usr/bin/env sh
. ${HOME}/.bashrc

if [ -d "$HOME/etc/bash_completion.d" ] ; then
	. $HOME/etc/bash_completion.d/*.bash
fi


if [ -f "${HOME}/.local/share/z/z.sh" ]; then
	. "${HOME}/.local/share/z/z.sh"
	. "${HOME}/.z.sh"
fi

. ${HOME}/.profile
. ${HOME}/.alias

export PATH="$HOME/.cargo/bin:$PATH"
