#!/bin/sh
#
# ~/.xinitrc
#
# # # # # # # # # # # # # #

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then

	xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
	xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then

	xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
	xmodmap "$usermodmap"
fi

# The source of my woes, the default being somewhat faulty, see I knew I wasn't crazy!

if [ -f "$HOME/.xprofile" ]; then
	source "$HOME/.xprofile"
fi

# Here Xfce is kept as default
#session=${1:-awesome}

#exec /home/tlh/.display-manager
exec awesome
# Gnome Keyring / seahorse require the following
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK
