#!/bin/env bash
#####################################################################
#####################    xprofile    ################################
#####################################################################
# sourced at boot by xinit and display managers like lightdm

export XDG_CONFIG_HOME="$HOME/.config"

# keyring and polkit daemons
## Gnome Keyring
gnome-keyring-daemon ---start --components=pkcs11 --login &


# PulseAudio
start-pulseaudio-x11 &

### Compositor
picom -b --experimental-backends --dbus --config $HOME/.config/picom.conf &

### Notifications
dunst &

### PulseAudio Tray Applet
# pa-applet &

### Network Manager Applet
#  nm-applet &

### Screen Saver
#  xscreensaver &

### Dropbox
dropbox &

## Merging Xresources
xrdb -load "$HOME"/.Xresources &

# Uncomment the below for an a e s t h e t i c sound to play at boot (commented out because it annoys my gf)
#sudo env -u SUDO_GID -u SUDO_COMMAND -u SUDO_USER -u SUDO_UID .local/share/bin/sound/BeverlyHillsCop
