#!/bin/sh
#####################################################################
#####################    xprofile    ################################
#####################################################################
# sourced at boot by xinit and display managers like lightdm

export XDG_CONFIG_HOME="$HOME/.config"

## Path Modifications
## Yes, I know this is unnecessary due to ~/.profile, but it is just to be sure since it can't hurt!
[ -d /sbin ] && PATH="$PATH:/sbin"
[ -d /usr/sbin ] && PATH="$PATH:/usr/sbin"
[ -d "$HOME/bin" ] && PATH="$HOME/bin:$PATH"
[ -d "$HOME/.local/share/bin" ] && PATH="$HOME/.local/share/bin:$PATH"

# keyring and polkit daemons
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

## Gnome Keyring
if (command -v gnome-keyring-daemon && ! pgrep gnome-keyring-d); then
	gnome-keyring-daemon ---start --components=pkcs11 --login &
	/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
fi

## Pulse Audio for X11
if (command -v start-pulseaudio-x11 && ! pgrep pulseaudio); then
	start-pulseaudio-x11 &
fi

## Function Definition
function run {
	if (command -v $1 && ! pgrep $1); then

		$@ &
	fi
}

## Functions

### Hitting Left Super == L Super + L Control + Escape (for rofi)
run xcape -e 'Super_L=Super_L|Control_L|Escape'

### Compositor
run picom -b --experimental-backends --dbus --config $HOME/.config/picom.conf

### Bluetooth Manager
run blueman-applet

### Notifications
run dunst

### PulseAudio Tray Applet
run pa-applet

### XFCE Settings
run xfsettingsd

### XFCE Power Manager
run xfce4-power-manager

### Network Manager Applet
run nm-applet

### Thinkpad Battery
run tp-battery-icon

### Screen Saver
run xscreensaver

### Dropbox
run ~/.dropbox-dist/dropboxd &

## Merging Xresources
xrdb -merge $HOME/.Xresources
