#!/bin/bash
##########################################################################################################
##########################################################################################################
## Thomas Leon Highbaugh  ################################################################################
## Dotfiles               ################################################################################
## ${HOME}/.bashrc        ################################################################################
##########################################################################################################
##########################################################################################################

## NVM Source ############################################################################################

export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                   # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion



##-----------------------------------------------------
## synth-shell-greeter.sh
if [ -f $HOME/.config/synth-shell/synth-shell-greeter.sh ] && [ -n "$( echo $- | grep i )" ]; then
	source $HOME/.config/synth-shell/synth-shell-greeter.sh
fi

##-----------------------------------------------------
## synth-shell-prompt.sh
if [ -f $HOME/.config/synth-shell/synth-shell-prompt.sh ] && [ -n "$( echo $- | grep i )" ]; then
	source $HOME/.config/synth-shell/synth-shell-prompt.sh
fi

##-----------------------------------------------------
## better-ls
if [ -f $HOME/.config/synth-shell/better-ls.sh ] && [ -n "$( echo $- | grep i )" ]; then
	source $HOME/.config/synth-shell/better-ls.sh
fi

##-----------------------------------------------------
## alias
if [ -f $HOME/.config/synth-shell/alias.sh ] && [ -n "$( echo $- | grep i )" ]; then
	source $HOME/.config/synth-shell/alias.sh
fi

##-----------------------------------------------------
## better-history
if [ -f $HOME/.config/synth-shell/better-history.sh ] && [ -n "$( echo $- | grep i )" ]; then
	source $HOME/.config/synth-shell/better-history.sh
fi

source $HOME/.profile
