#!/bin/env bash
###########################################################################
# Aliases
#
#
# Thomas Leon Highbaugh
# Github: https://github.com/Thomashighbaugh
###########################################################################

## Dotfiles Location ###########################################################

for file in $(
	find "$HOME"/dotfiles/home/shell/alias -name '*.alias.sh'
); do
	source "$file"
done
