#!/bin/env bash
################################################################################
## .profile ####################################################################
################################################################################
## This file setsenvironmental variables available across the shells installed on
## the system. Edit with care
################################################################################
## Config Directory
################################################################################

## Dotfiles Location ###########################################################

for file in $(
    find "$HOME"/dotfiles/home/shell/configs -name '*.config.sh'
); do
    source "$file"
done

for file in $(
    find "$HOME"/dotfiles/home/shell/alias -name '*.aliases.sh'
); do
    source "$file"
done

# shellcheck source=/dev/null
source "$HOME"/dotfiles/home/shell/aliases



# Because this comes up more often than is natural but will not clear any other way thanks to ccache
export CC="gcc"
export NO_AT_BRIDGE=1

export PATH="/home/tlh/.local/share/solana/install/active_release/bin:$PATH"

export PATH=$PATH:/usr/local/go/bin

export PATH=$PATH:$HOME/.local/bin
