# /etc/zshenv: user specific .zshenv file for zsh(1).
#
# Sourced on all invocations of the shell.
#
# Global Order: zshenv, zprofile, zshrc, zlogin

export OS=`uname -s`

export EDITOR="vim"
export PAGER="less"
export LESS="-RMin"
export EMAIL="thighbaugh@zoho.com"
export ARCH=`uname -m`


export SAVEHIST=9999
export HISTSIZE=9999
export HISTFILE=$HOME/.history
export HIST_EXPIRE_DUPS_FIRST=true
export GO15VENDOREXPERIMENT=1
export RI_PAGER='less -FX'


# set PATH so it includes user's private bin if it exists
if [[ -d "$HOME/bin" ]]; then
	PATH="$HOME/bin:$PATH"
fi

# xdg-derived, systemd file-hierarchy
if [[ -d "$HOME/.local/bin" ]]; then
	PATH="$HOME/.local/bin:$PATH"
fi

if [[ -d "$HOME/.files/bin" ]]; then
	PATH="$HOME/.files/bin:$PATH"
fi

# go
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$PATH # shiftin GOPATH bins
export OS=`uname -s`
export EDITOR="vim"
export PAGER="less"
export LESS="-RMin"
export EMAIL="thighbaugh@zoho.com"
export ARCH=`uname -m`
export SAVEHIST=9999
export HISTSIZE=9999
export HISTFILE=$HOME/.history
export HIST_EXPIRE_DUPS_FIRST=true
export GO15VENDOREXPERIMENT=1
export RI_PAGER='less -FX'


# Color man pages
export LESS_TERMCAP_mb=$'\E[01;32m'
export LESS_TERMCAP_md=$'\E[01;32m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;47;34m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;36m'
export LESS=-r


