#!/bin/sh

# set PATH so it includes user's private bin if it exists
if [[ -d "$HOME/bin" ]]; then
	PATH="$HOME/bin:$PATH"
fi

# xdg-derived, systemd file-hierarchy
if [[ -d "$HOME/.local/bin" ]]; then
	PATH="$HOME/.local/bin:$PATH"
fi

if [[ -d "$HOME/.files/bin" ]]; then
	PATH="$HOME/.files/bin:$PATH"
fi

unset EDITOR
unset EDITORD

if [[ -s $(which nvim) ]]; then
	export EDITOR=nvim
elif [[ -s $(which vim) ]]; then
	export EDITOR=vim
else
	export EDITOR=vi
fi

export EDITORD=${EDITORD:-$EDITOR}

source ~/.zsh-nvm/zsh-nvm.plugin.zsh

