#!/bin/sh
export XDG_CONFIG_HOME="$HOME/.config"

[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh
[ -f /usr/local/etc/profile.d/z.sh ] && . /usr/local/etc/profile.d/z.sh


if [ -d "$XDG_CONFIG_HOME/yarn/global/node_modules/.bin" ]; then
  export PATH="$XDG_CONFIG_HOME/yarn/global/node_modules/.bin:$PATH"
fi

if [ -d "$HOME/.yarn/bin" ]; then
  export PATH="$HOME/.yarn/bin:$PATH"
fi

if [ -d "$HOME/.cargo/bin" ]; then
  export PATH="$HOME/.cargo/bin:$PATH"
fi

if [ -d "$HOME/.gem/ruby/2.6.0" ]; then
	export PATH="$HOME/.gem/ruby/2.6.0:$PATH"
fi
export EDITOR=/usr/bin/nvim
export EDITORD=/usr/bin/nvim
export QT_QPA_PLATFORMTHEME="qt5ct"
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export XDG_CURRENT_DESKTOP=XFCE
export XDG_CONFIG_DIRS=/etc/xdg
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$PATH # shiftin GOPATH bins
# go
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$PATH # shiftin GOPATH bins
export OS=`uname -s`
export PAGER="less"
export LESS="-RMin"
export EMAIL="thighbaugh@zoho.com"
export ARCH=`uname -m`
export SAVEHIST=9999
export HISTSIZE=9999
export HISTFILE=$HOME/.history
export HIST_EXPIRE_DUPS_FIRST=true
export GO15VENDOREXPERIMENT=1
export RI_PAGER='less -FX'


# Color man pages
export LESS_TERMCAP_mb=$'\E[01;32m'
export LESS_TERMCAP_md=$'\E[01;32m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;47;34m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;36m'
export LESS=-r

source $HOME/.aliases

