#!/bin/sh
##########################################################################################################
## .profile ######################################################################################
##########################################################################################################

## This file setsenvironmental variables available across the shells installed on
## this system. Edit with care, or learn to use startx ;]

################################################################################
## Config Directory
################################################################################

## Order Matters
source $HOME/dotfiles/topics/sh/variables/variables.posix.sh

source $HOME/dotfiles/topics/sh/path/path.posix.sh

source $HOME/dotfiles/topics/sh/keychain/keychain.posix.sh

[ -z "$NVM_DIR" ] && export NVM_DIR="$HOME/.nvm"
source /usr/share/nvm/nvm.sh

source /usr/share/nvm/bash_completion

source /usr/share/nvm/install-nvm-exec


