#!/bin/sh
##########################################################################################################
## .profile ######################################################################################
##########################################################################################################

## This file setsenvironmental variables available across the shells installed on
## this system. Edit with care, or learn to use startx ;]

################################################################################
## Config Directory
################################################################################

## Order Matters hence no looping structure ;]
source $HOME/dotfiles/topics/sh/configs/variables.posix.sh

source $HOME/dotfiles/topics/sh/configs/path.posix.sh

source $HOME/dotfiles/topics/sh/configs/keychain.posix.sh

source $HOME/dotfiles/topics/sh/configs/variables.posix.sh
# Adds in system wide NVM

[ -z "$NVM_DIR" ] && export NVM_DIR="$HOME/.nvm"
source /usr/share/nvm/nvm.sh

source /usr/share/nvm/bash_completion

source /usr/share/nvm/install-nvm-exec

# Adds in rbenv

eval "$(rbenv init -)"

source "$HOME/.aliases"

[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

# vim: set ft=sh:
