#!/bin/sh
##########################################################################################################
## .profile ######################################################################################
##########################################################################################################

## This file setsenvironmental variables available across the shells installed on
## this system. Edit with care, or learn to use startx ;]

################################################################################
## Config Directory
################################################################################

## Dotfiles Location ###########################################################
cd "$(readlink ~/.zshrc | xargs dirname)"
export DOTFILES="$(git rev-parse --show-toplevel)"
cd - >/dev/null

for file in $(
	find "$DOTFILES/topics/sh/configs" -name '*.posix.sh'
); do
	source "$file"
done

#[ -z "$NVM_DIR" ] && export NVM_DIR="$HOME/.nvm"
#source /usr/share/nvm/nvm.sh

#source /usr/share/nvm/bash_completion

#source /usr/share/nvm/install-nvm-exec

source "$HOME/dotfiles/topics/sh/aliases"

## scm #########################################################################

export SCM_WORKSPACE_DIR="~/Dropbox/Workspace/Repositories"         # defaults to ~/Workspace
export SCM_WORKSPACE_DIR_DEFAULT_PERM="0755"  # defaults to 0755

export SCM_POST_CLONE_CMD=""  # defaults to ""

# vim: set ft=sh:
