#!/usr/bin/env sh

# set PATH so it includes user's private bin if it exists
if [[ -d "$HOME/bin" ]]; then
	PATH="$HOME/bin:$PATH"
fi

# xdg-derived, systemd file-hierarchy
if [[ -d "$HOME/.local/bin" ]]; then
	PATH="$HOME/.local/bin:$PATH"
fi

if [[ -d "$HOME/.files/bin" ]]; then
	PATH="$HOME/.files/bin:$PATH"
fi

source "$HOME/.alias"



export PATH=$GOPATH/bin:$PATH # shiftin GOPATH bins

# added by travis gem
[ -f $HOME/.travis/travis.sh ] && source $HOME/.travis/travis.sh


[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh
[ -f /usr/local/etc/profile.d/z.sh ] && . /usr/local/etc/profile.d/z.sh
# macos
[ -f /usr/local/opt/chruby/share/chruby/chruby.sh ] && . /usr/local/opt/chruby/share/chruby/chruby.sh
# arch
[ -f /usr/share/chruby/chruby.sh ] && . /usr/share/chruby/chruby.sh

# macos
[ -f /usr/local/opt/chruby/share/chruby/auto.sh ] && . /usr/local/opt/chruby/share/chruby/auto.sh
# arch
[ -f /usr/share/chruby/auto.sh ] && . /usr/share/chruby/auto.sh

if [[ -s $(type chruby) ]]; then
	chruby 2.6.0
fi

# vim: set ft=sh:
