#!/bin/env bash
################################################################################
## .profile ####################################################################
################################################################################
## This file setsenvironmental variables available across the shells installed on
## the system. Edit with care
################################################################################
## Config Directory
################################################################################

## Dotfiles Location ###########################################################

for file in $(
  find "$HOME"/dotfiles/home/sh/configs -name '*.posix.sh'
); do
  source "$file"
done

# shellcheck source=/dev/null
source "$HOME"/dotfiles/home/sh/aliases



. "$HOME/.cargo/env"

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
