#!/bin/env bash
################################################################################
## .profile ####################################################################
################################################################################
## This file setsenvironmental variables available across the shells installed on
## the system. Edit with care
################################################################################
## Config Directory
################################################################################

## Dotfiles Location ###########################################################
cd "$(readlink ~/.zshrc | xargs dirname)" || return
export DOTFILES="$(git rev-parse --show-toplevel)"
cd - >/dev/null || return
# shellcheck source=/dev/null
for file in $(find  "$DOTFILES"/home/sh/configs -name '*.posix.sh'
    ); do
    source "$file"
done

# shellcheck source=/dev/null
source "$HOME"/dotfiles/home/sh/aliases
source "$HOME/.cargo/env"
