#!/usr/bin/env sh
. ${HOME}/.bashrc

if [ -d "$HOME/etc/bash_completion.d" ] ; then
	. $HOME/etc/bash_completion.d/*.bash
fi


if [ -f "${HOME}/.local/share/z/z.sh" ]; then
	. "${HOME}/.local/share/z/z.sh"
	. "${HOME}/.z.sh"
fi

. ${HOME}/.profile
. ${HOME}/.aliases

export PATH="$HOME/.cargo/bin:$PATH"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
_byobu_sourced=1 . /usr/bin/byobu-launch 2>/dev/null || true
