#!/bin/env bash
################################################################################
## .profile ####################################################################
################################################################################
## This file setsenvironmental variables available across the shells installed on
## the system. Edit with care
################################################################################
## Config Directory
################################################################################

## Dotfiles Location ###########################################################

for file in $(
  find "$HOME"/dotfiles/home/sh/configs -name '*.posix.sh'
); do
  source "$file"
done

# shellcheck source=/dev/null
source "$HOME"/dotfiles/home/sh/aliases


if [[ -f $HOME/.cargo/env ]]; then
    source $HOME/.cargo/env
fi

